#!/usr/bin/env sh
FILE=`pwd`/typefi2bookxml.platypus
TMPL=`pwd`/typefi2bookxml.platypus.tmpl
REPLACE=`pwd`

rm $FILE
sed "s/REPLACE_PWD/$(echo $REPLACE | sed -e 's/\\/\\\\/g' -e 's/\//\\\//g' -e 's/&/\\\&/g')/g" $TMPL > $FILE
